# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fluxion.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "fluxion.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rfluxion.proto\x12\x07\x66luxion"*\n\x0bInitRequest\x12\x0e\n\x06policy\x18\x01 \x01(\t\x12\x0b\n\x03jgf\x18\x02 \x01(\t"\x81\x01\n\x0cInitResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .fluxion.InitResponse.ResultType"?\n\nResultType\x12\x10\n\x0cINIT_SUCCESS\x10\x00\x12\x0e\n\nINIT_ERROR\x10\x01\x12\x0f\n\x0bINIT_DENIED\x10\x02"E\n\x0cMatchRequest\x12\x0f\n\x07jobspec\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\t\x12\x13\n\x0breservation\x18\x03 \x01(\x08"\xd9\x01\n\rMatchResponse\x12\x12\n\nallocation\x18\x01 \x01(\t\x12\r\n\x05jobid\x18\x02 \x01(\x03\x12\x10\n\x08reserved\x18\x03 \x01(\x08\x12\n\n\x02\x61t\x18\x04 \x01(\x03\x12\x10\n\x08overhead\x18\x05 \x01(\x02\x12\x31\n\x06status\x18\x06 \x01(\x0e\x32!.fluxion.MatchResponse.ResultType"B\n\nResultType\x12\x11\n\rMATCH_SUCCESS\x10\x00\x12\x0f\n\x0bMATCH_ERROR\x10\x01\x12\x10\n\x0cMATCH_DENIED\x10\x02"\x1e\n\rCancelRequest\x12\r\n\x05jobID\x18\x02 \x01(\x03"\xc3\x01\n\x0e\x43\x61ncelResponse\x12\r\n\x05jobID\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\x05\x12\x32\n\x06status\x18\x03 \x01(\x0e\x32".fluxion.CancelResponse.ResultType"_\n\nResultType\x12\x12\n\x0e\x43\x41NCEL_SUCCESS\x10\x00\x12\x18\n\x14\x43\x41NCEL_REQUEST_ERROR\x10\x01\x12\x10\n\x0c\x43\x41NCEL_ERROR\x10\x02\x12\x11\n\rCANCEL_DENIED\x10\x03\x32\xbe\x01\n\x0e\x46luxionService\x12\x38\n\x05Match\x12\x15.fluxion.MatchRequest\x1a\x16.fluxion.MatchResponse"\x00\x12;\n\x06\x43\x61ncel\x12\x16.fluxion.CancelRequest\x1a\x17.fluxion.CancelResponse"\x00\x12\x35\n\x04Init\x12\x14.fluxion.InitRequest\x1a\x15.fluxion.InitResponse"\x00\x42\x39Z7github.com/converged-computing/fluxion/pkg/fluxion-grpcb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "fluxion_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"Z7github.com/converged-computing/fluxion/pkg/fluxion-grpc"
    _globals["_INITREQUEST"]._serialized_start = 26
    _globals["_INITREQUEST"]._serialized_end = 68
    _globals["_INITRESPONSE"]._serialized_start = 71
    _globals["_INITRESPONSE"]._serialized_end = 200
    _globals["_INITRESPONSE_RESULTTYPE"]._serialized_start = 137
    _globals["_INITRESPONSE_RESULTTYPE"]._serialized_end = 200
    _globals["_MATCHREQUEST"]._serialized_start = 202
    _globals["_MATCHREQUEST"]._serialized_end = 271
    _globals["_MATCHRESPONSE"]._serialized_start = 274
    _globals["_MATCHRESPONSE"]._serialized_end = 491
    _globals["_MATCHRESPONSE_RESULTTYPE"]._serialized_start = 425
    _globals["_MATCHRESPONSE_RESULTTYPE"]._serialized_end = 491
    _globals["_CANCELREQUEST"]._serialized_start = 493
    _globals["_CANCELREQUEST"]._serialized_end = 523
    _globals["_CANCELRESPONSE"]._serialized_start = 526
    _globals["_CANCELRESPONSE"]._serialized_end = 721
    _globals["_CANCELRESPONSE_RESULTTYPE"]._serialized_start = 626
    _globals["_CANCELRESPONSE_RESULTTYPE"]._serialized_end = 721
    _globals["_FLUXIONSERVICE"]._serialized_start = 724
    _globals["_FLUXIONSERVICE"]._serialized_end = 914
# @@protoc_insertion_point(module_scope)
